apiVersion: v1
kind: Service
metadata:
  labels:
    app: actions
  name: actions
spec:
  ports:
    - name: "webapp"
      port: 8080
      targetPort: 8080
  selector:
    app: actions
status:
  loadBalancer: {}
