apiVersion: v1
kind: Service
metadata:
  labels:
    app: configurer
  name: configurer
spec:
  ports:
    - name: "webapp"
      port: 8080
      targetPort: 8080
  selector:
    app: configurer
status:
  loadBalancer: {}
