apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: balancer
  name: balancer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: balancer
  strategy: {}
  template:
    metadata:
      labels:
        app: balancer
    spec:
      containers:
        - name: balancer
          # image: abatalev/balancer:2021-10-28
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 20
          resources:
            requests:
              cpu: 10m
              memory: 256Mi
      restartPolicy: Always
status: {}
