apiVersion: v1
kind: Service
metadata:
  labels:
    app: balancer
  name: balancer
spec:
  ports:
    - name: "webapp"
      port: 8080
      targetPort: 8080
  selector:
    app: balancer
status:
  loadBalancer: {}