apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: actions
  labels:
    release: stand
    app: actions
spec:
  endpoints:
  - port: webapp
    path: '/actuator/prometheus'
  namespaceSelector:
    any: true
  selector:
    matchLabels:
      app: actions
