balancer-chart:
  image:
    repository: abatalev/balancer
    tag: "efd8272b"
configurer-chart:
  image:
    repository: abatalev/configurer
    tag: "477f4708"
actions-chart:
  image:
    repository: abatalev/actions
    tag: "84c6e058"
initdb-chart:
  image:
    repository: abatalev/initdb
    tag: "884d9d84"
postgresql:
  fullnameOverride: db
  postgresqlDatabase: postgres
  postgresqlPassword: example
  resources:
    requests:
      cpu: 100m
  metrics:
    enabled: false
    serviceMonitor:
      enabled: false
  volumePermissions:
    enabled: false
    securityContext:
      runAsUser: "auto"
  securityContext:
    enabled: false
  shmVolume:
    chmod:
      enabled: false
  containerSecurityContext:
    enabled: false
ibm-mqadvanced-server-dev:
  fullnameOverride: mq0
  resources:
    requests:
      cpu: 100m
    limits:
      cpu: 100m
  nameOverride: mq
  license: accept
  metrics:
    enabled: false
  log:
    debug: true
  image:
    tag: 9.2.3.0-r1
  queueManager:
    dev:
      secret:
        name: mq-secret
        adminPasswordKey: adminPassword
    name: MQ1
jaeger-all-in-one:
  fullnameOverride: jaeger
  resources:
    requests:
      cpu: 20m
